paths:
  # The directories can be either relative or absolute path.
  assets-dir: 'assets'
  binaries-dir: 'binaries'
  git-clones-dir: 'git-clones'

general:
  GitHub:
    gitToken: '' # WIP
    gitRateLimit: # WIP
      count: 10 # WIP do not make more than X call per [timeout] minutes
      timeout: 60 # WIP

builds: # List of GitHub repos
  # Inference of Meta's LLaMA model (and others) in pure C/C++
  llama-server:
    check-updates:
      false
    update-type: 'git-release'
    git-releases:
      url: 'https://api.github.com/repos/ggml-org/llama.cpp/releases'
      type: 'linux'
      subtype: 'general'
      archive-pattern:
        'linux':
          binaries: # These entries will be marked as executables.
            'server': 'build/bin/llama-server'
          subtypes:
            'general': 'llama-b*-bin-ubuntu-x64.zip'
            'vulkan': 'llama-b*-bin-ubuntu-vulkan-x64.zip'

  # whisply combines faster-whisper and insanely-fast-whisper to offer an easy-to-use solution for batch processing files on Windows, Linux and Mac. It also enables word-level speaker annotation by integrating whisperX and pyannote.
  whisply:
    check-updates:
      true
    update-type: 'git-repo'
    post-clone-commands:
      - 'pip install .'
    git-clone:
      'repo': 'https://github.com/tsmdt/whisply'
      'branch': 'main'