llama-server:
  git-releases:
    url: 'https://api.github.com/repos/ggml-org/llama.cpp/releases'
    type: 'linux'
    subtype: 'general'

    archive-pattern:
      'linux':
        binaries:
          'server': 'build/bin/llama-server'
        subtypes:
          'general': 'llama-b*-bin-ubuntu-x64.zip'
          'vulkan': 'llama-b*-bin-ubuntu-vulkan-x64.zip'

  check-updates:
    true

